---
title: "Part 2 Appendix"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Create matrix with dimensions 40 by 1000 filled with exponentialy 
#distributed data and find the mean for each simulation:
n<- 40
simulations <- 1000
lambda<-.2
mu<- apply(matrix(data =rexp(n*simulations, rate= lambda), 
                  nrow=n, ncol=simulations), 2, mean)


#Calculate sample mean versus theoretical mean:
smean<- mean(apply(matrix(data =rexp(n*1000, rate= lambda), 
                          nrow=n, ncol=simulations), 2, mean))
tmean<- 1/lambda

#Calculate sample varience versus theoretical varience:
ssdt<- sd(apply(matrix(data =rexp(n*1000, rate= lambda), 
                       nrow=n, ncol=simulations), 2, mean))
tsdt<- (1/lambda)/sqrt(n)

#open libraries ggplot2 and gridExtra:
library(ggplot2)
library(gridExtra)

#create density histogram for sample means
g1<- ggplot(data=data.frame(mu), aes(mu))+
    geom_histogram(aes(y = ..density..), colour="black", fill="white") +
    geom_density(alpha = 0.2, fill = "#FF6666")+
    labs(title="Sample Mean", x="")

#create density histogram for distribution variable example:
expvar<- rexp(simulations, rate =.2)
g2<- ggplot(data=data.frame(expvar), aes(expvar))+
    geom_histogram(aes(y = ..density..), colour="black", fill="white")+
    geom_density(alpha = 0.2, fill = "#FF6666")+
    labs(title="Exponential", x="")

#create density histogram for normal distribution example:
randvar<- rnorm(simulations)
g3<- ggplot(data=data.frame(randvar), aes(randvar))+
    geom_histogram(aes(y = ..density..), colour="black", fill="white")+
    geom_density(alpha = 0.2, fill = "#FF6666")+ 
    labs(title="Normal", x="")

#arrange all three graphs on one page 
grid.arrange(g1, g2, g3, nrow = 1)
```

